### ISSUE TITLE
JWK object and AES unwrap key

### ISSUE THREAD

**Issue by SravanPeddi** [airsidemobile/JOSESwift#302] opened 2023-12-01 10:44 UTC
Hi Team,

I am unable to create a JWK object and unable to use unwrapkey method.

Can you please provide sample?

**Comment by daniel-moh** [comment] 2024-08-28 09:21
I'm closing this since there's not nearly enough information for us to understand what this is about. Feel free to re-open this with a more detailed, reproducible example @SravanPeddi.

**Closed by daniel-moh** 2024-08-28 09:21 UTC
