### ISSUE TITLE
how to get privateKey with RSAPrivateKey

### ISSUE THREAD

**Issue by phucnd0604** [airsidemobile/JOSESwift#165] opened 2019-07-26 05:16 UTC
Please help me to convert jwk to private with RSAPrivateKey
the protocol ExpressibleAsRSAPrivateKeyComponents is not implement

**Comment by daniel-mohemian** [comment] 2019-07-30 13:22
Hi @phucnd0604 👋 

That is correct, `ExpressibleAsRSAPrivateKeyComponents` is not implemented at the moment. We currently have no plans to implement it ourselves as the main use case (sharing private keys over the network) is not something we're comfortable with. However, if you have an implementation ready, we'd be happy to review and discuss a pull request.

To instantiate a `SecKey` from a JWK, you need to get the JWK into a format accepted by [`SecKeyCreateWithData`](https://developer.apple.com/documentation/security/1643701-seckeycreatewithdata). As discussed [in the docs](https://developer.apple.com/documentation/security/1643698-seckeycopyexternalrepresentation) this is "_PKCS#1 format for an RSA key_". The format specification can be found [here](https://tools.ietf.org/html/rfc8017#appendix-A.1.2).

I'll close this issue for now as it is not a bug of a feature we'll be handling now. But feel free to post in this thread if you have further questions.

And again, be careful about sharing private keys over the network!

**Closed by daniel-mohemian** 2019-07-30 13:22 UTC
